spring :
  datasource :
    url : jdbc:mysql://localhost:3307/library_managementSystem_yasas?createDatabaseIfNotExist=true
    username : root
    password : yasas

  jpa :
    hibernate :
      ddl-auto : update

server:
  port : 8085

